### ISSUE TITLE
Zepto incompatible with Bootstrap 3

### ISSUE THREAD

**Issue by mossroy** [madrobby/zepto#791]
I was using happily Bootstrap 2 with Zepto, integrated thorugh require.js.

Today I've tried to integrate Bootstrap 3 (very recently released as RC1) with Zepto.
It seems to work for basic things, but if failed when I tried to use the "responsive navbars" feature of Bootstrap 3 : http://twitter.github.io/bootstrap/components/#navbar-responsive
If you resize the screen to a small width, the navbar collapses into a button.
If you click this button, it should display the menu.
It works correctly when using jQuery, but does not when using Zepto v1.0-1-ga3cab6c instead.
It gives the following error message : 
TypeError: str is undefined
at line 103 of zepto.js (my line numbers are probably not accurate because I added lines to integrate zepto with require.js). Anyway, it is in function dasherize : 
return str.replace(/::/g, '/')

If I put a breakpoint on this line, I see it is called by line 657 of bootstrap.js (again, line number not accurate) : 
var option  = data ? 'toggle' : $this.data()
It is in under comment // COLLAPSE DATA-API

I think it might simply come from the fact that jQuery handles a call of data() with no arguments. In this case, it seems to return a list of the data elements : http://api.jquery.com/data/
And it seems that Zepto does not support a call to data() with no arguments, because the first instruction of this function is : 
var data = this.attr('data-' + dasherize(name), value)

**Comment by mancvso** [comment]
Yes, please, a working gist will be helpful, specially for my use-case.

**Comment by cancerberoSgx** [comment]
in my case, bootstrap 3.3.5, Zepto 1.1.6 - modules :  zepto event ajax form ie selector deferred data, and it fails in bootstra.js#13 : 
  var version = $.fn.jquery.split(' ')[0].split('.')

(split is not a function)

**Comment by sdaitzman** [comment]
Bootstrap 4 alpha is now out! If I get a chance, I'll test with Zepto. :smile:

**Comment by madrobby** [comment]
Closing this because there was no response to our questions in a while. Feel free to reopen with the requested information!

**Comment by apetrichkovich** [comment]
Custom Bootstrap 3.4 does not work with Zepto 1.2.0:
var e=t.fn.jquery.split(" ")[0].split(".")    ==>    Uncaught TypeError: Cannot read property 'split' of undefined

PS. It is similar issue like @cancerberoSgx posted. Is there some solution for Bootstrap 3.4?
