### ISSUE TITLE
removeClass not work in android 2.1

### ISSUE THREAD

**Issue by liuhann** [madrobby/zepto#390]
It works fine in chrome.  but in android 2.1 simulator,  

I got this 
02-06 06:19:27.533: D/PhoneGapLog(288): file:///android_asset/www/zepto.js: Line 390 : TypeError: Result of expression 'classList.trim' [undefined] is not a function.
